language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: sNJQXWkB//P8JhsdLQKhFbKeCcJ2sb6FiEDpqK5UwFGMt9NRnqFCxDHVxpmr61uPB2XmJr5WdhpeOH6TXttEM31QRuBWg02XbXLEhCgQESh/wg5Ro76OSRZ71iAYXLwFxlkdJ3qgVm0hnLjLTKmYuKu7C1E5bH9/wma1S8Y4PLM=
  - secure: kez8ylnc99MwHpXNBvUZ3iweAbiXO04NBxB/mRxpl/KF3ZBPwokmd23yoGztm5SRuBTKdpQAXSEryDF2VbE4Pqz94kxxJKqizahGRJJt9JOThZZHhdNoUt44wLz6YLh5RmiYQe/3JFwBxbdyBeEE5Vud2I8Yy7o+dR+c7aztSSk=
  - secure: tcFLn8fgP/gxtZQC2iO70tABBOrqB/CFvAfWj9sr069mc6STaVahVol7Wo77cDr4WkrtvpMVXe/laeqsKyMe7vUVbGSuby8tJOrOK5LNuTfgmvS3OFmXCRYsyCa806ft/CLv4nw9Ld8IQGRMXUQCK1wAm6xhRLQF5MMTDQkiqiQ=
addons:
  ssh_known_hosts:
  - 128.199.54.7
script: ./node_modules/.bin/docpad generate --silent --env production
branches:
  only:
  - master
after_success:
- sudo apt-get -y -qq install sshpass
- rsync -arlptzO --delete --stats --rsh="sshpass -p $DEPLOY_PASSWORD ssh -l $DEPLOY_USER" ./out/ 128.199.54.7:$DEPLOY_DEST
